api:
  documentation:
    header: "Fizz Buzz API Documentation"
    description: "Fizz Buzz Demo Application"
    version: "1.0.0"
    license:
      name: "Apache 2.0"
      url: "http://www.apache.org/licenses/LICENSE-2.0"
    contact:
      name: "Boris Sukhodoev"
      url: ""
      email: "boris.sukhodoev@gmail.com"

server:
  tomcat:
    max-http-post-size: 16384